name       : miniupnpc
version    : 2.0.20170509
release    : 3
source     :
    - http://miniupnp.free.fr/files/miniupnpc-2.0.20170509.tar.gz : d3c368627f5cdfb66d3ebd64ca39ba54d6ff14a61966dbecb8dd296b7039f16a
license    : BSD-3-Clause
component  : programming
summary    : A small UPnP client library/tool to access Internet Gateway Devices
description: |
    A small UPnP client library/tool to access Internet Gateway Devices
setup      : |
    %patch -p2 < $pkgfiles/security/cve-2017-1000494.patch
    %cmake -DUPNPC_BUILD_STATIC=FALSE .
build      : |
    %make
install    : |
    %make_install
