name       : miniupnpc
version    : '2.1'
release    : 4
source     :
    - https://github.com/miniupnp/miniupnp/archive/miniupnpc_2_1.tar.gz : 19c5b6cf8f3fc31d5e641c797b36ecca585909c7f3685a5c1a64325340537c94
license    : BSD-3-Clause
component  : programming.library
summary    : A small UPnP client library/tool to access Internet Gateway Devices
description: |
    A small UPnP client library/tool to access Internet Gateway Devices
build      : |
    pushd miniupnpc
    %make
install    : |
    pushd miniupnpc
    %make_install
    rm $installdir/usr/lib/libminiupnpc.a