name       : miniupnpc
version    : 1.9.20160209
release    : 1
source     :
    - http://miniupnp.free.fr/files/miniupnpc-1.9.20160209.tar.gz : 572171eacc1d72537ce47b6f4571260757ab7bcfdaf54c3a55c7f88594d94b6f
license    : BSD-License
component  : programming
summary    : A small UPnP client library/tool to access Internet Gateway Devices
description: |
    A small UPnP client library/tool to access Internet Gateway Devices
setup      : |
    %cmake -DBUILD_SHARED_LIBS=ON .
build      : |
    %make
install    : |
    %make_install
